# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Drawers Surplus
email: yves@film-storyboards.com
description: Drawings, rough sketches, storyboards and concept illustrations accumulated in the drawers over the years # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  YJPL

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: FilmStoryboards

# Build settings
markdown: kramdown
#theme: jekyll-athena

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2

# Reading Files
include:
  - .htaccess
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:

#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Archives
tag_archive:
  type: liquid
  path: /tags/
# Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: 'all'
  layout: 'archive-taxonomy'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
  category_archive:
    type: liquid
  timezone: Europe/Paris

# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: false

  # Category pages, omit entire config element to disable
  categories:
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - 'archive-taxonomy.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
#    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
#    permalink: '/category/:cat'

  # Collection pages, omit to disable
#  collections:
#    layouts:
#      - 'autopage_collection.html'
#    title: 'Posts in collection :coll' # :coll is replaced by the collection name
#    permalink: '/collection/:coll'

  # Tag pages, omit to disable
  tags:
    layouts:
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'
